services:
  db:
    container_name: postgres_db
    restart: always
    image: postgres

    ports:
      - "5432:5432"
    environment:
        POSTGRES_USER: "burguer"
        POSTGRES_DB: "burguer"
        POSTGRES_PASSWORD: "SuperPassword@2"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
