services:
  db:
    container_name: db
    restart: always
    image: postgres

    ports:
      - "5432:5432"
    environment:
        POSTGRES_USER: "burguer"
        POSTGRES_DB: "burguer"
        POSTGRES_PASSWORD: "SuperPassword@2"
